"""Some changes in deals

Revision ID: 38724073e778
Revises: 4f3abc10125b
Create Date: 2026-05-02 05:57:40.353411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38724073e778'
down_revision: Union[str, Sequence[str], None] = '4f3abc10125b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deals', sa.Column('last_action_by', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deals', 'last_action_by')
    # ### end Alembic commands ###
