"""Some changes in deals

Revision ID: 4f3abc10125b
Revises: 8a801dd21474
Create Date: 2026-05-02 05:52:53.961934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f3abc10125b'
down_revision: Union[str, Sequence[str], None] = '8a801dd21474'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deals', sa.Column('cancel_reason', sa.String(), nullable=True))
    op.add_column('deals', sa.Column('change_reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deals', 'change_reason')
    op.drop_column('deals', 'cancel_reason')
    # ### end Alembic commands ###
