"""Some changes in deals

Revision ID: 8a801dd21474
Revises: dd92d1eb39be
Create Date: 2026-05-01 15:39:07.485017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a801dd21474'
down_revision: Union[str, Sequence[str], None] = 'dd92d1eb39be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deals', sa.Column('worker_completed_at', sa.DateTime(), nullable=True))
    op.add_column('deals', sa.Column('client_completed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deals', 'client_completed_at')
    op.drop_column('deals', 'worker_completed_at')
    # ### end Alembic commands ###
