"""Added unique columns at JobResponse model

Revision ID: bde39402eea9
Revises: e2f992581ebc
Create Date: 2026-04-29 15:30:13.056146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bde39402eea9'
down_revision: Union[str, Sequence[str], None] = 'e2f992581ebc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uniq_job_worker_response', 'job_responses', ['job_id', 'worker_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uniq_job_worker_response', 'job_responses', type_='unique')
    # ### end Alembic commands ###
