"""Added response statuses

Revision ID: be9b08e15fba
Revises: bde39402eea9
Create Date: 2026-04-29 16:16:40.670397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be9b08e15fba'
down_revision: Union[str, Sequence[str], None] = 'bde39402eea9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    response_status = sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', name='response_status')
    response_status.create(op.get_bind())
    op.add_column('job_responses', sa.Column('status', response_status, nullable=False, server_default='PENDING'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_responses', 'status')
    sa.Enum(name='response_status').drop(op.get_bind())
    # ### end Alembic commands ###
