"""Added indexes in jobs

Revision ID: c15f6bcf4f10
Revises: 37a0d7e95d2d
Create Date: 2026-05-05 08:39:35.433658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c15f6bcf4f10'
down_revision: Union[str, Sequence[str], None] = '37a0d7e95d2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_jobs_expires_at'), 'jobs', ['expires_at'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_expires_at'), table_name='jobs')
    # ### end Alembic commands ###
