"""Added job types

Revision ID: e2f992581ebc
Revises: d280823b28ba
Create Date: 2026-04-28 09:23:09.574585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2f992581ebc'
down_revision: Union[str, Sequence[str], None] = 'd280823b28ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('type', sa.Enum('ASSEMBLY', 'MOUNTING', 'HANDYMAN', 'CLEANING', 'MOVING', 'ELECTRICAL', 'PLUMBING', 'YARDWORK', 'DELIVERY', 'REPAIR', 'TECH', name='job_type'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'type')
    # ### end Alembic commands ###
